/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Sales;

import Classes.AbstractClasses.Order;
import static Classes.Functions.Orders.listOrders;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nkanabo
 */
public class ReturnProduct extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    /*Sales variables declaration*/
    int row, column, clickcount;
    Object[] columnNames = {"Select", "Order Id", "Product",
        "Quantity", "List price", "Discount"
    };
    ArrayList<Order> ReturnList;

    DefaultTableModel ReturnModel = new DefaultTableModel(0, 0) {
        @Override
        public Class getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return Boolean.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;
                default:
                    return String.class;
            }
        }
    };

    public ArrayList<String> prd_details = new ArrayList<>();

    /*End of variables declaration*/
    public ReturnProduct() throws SQLException, ClassNotFoundException, ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        ReturnList = new ArrayList<>();
        // add header in table model     
        ReturnModel.setColumnIdentifiers(columnNames);
        OrdersTable.setModel(ReturnModel);

        loadJtableValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        front = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        ReturnSaleBody = new javax.swing.JPanel();
        SelectionMeans = new javax.swing.JPanel();
        by_order3 = new javax.swing.JRadioButton();
        by_order2 = new javax.swing.JRadioButton();
        by_order1 = new javax.swing.JRadioButton();
        by_order = new javax.swing.JRadioButton();
        SelectRow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();
        SelectAmount = new javax.swing.JPanel();
        SelectionArea = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        qtyamounttobereturned = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        prdnametobereturned = new javax.swing.JLabel();
        ReturnMethod = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        SelectShipping = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setBorder(new javax.swing.border.MatteBorder(null));

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-back-16.png"))); // NOI18N
        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        front.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        front.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-forward-16.png"))); // NOI18N
        front.setText("Next");
        front.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        front.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frontMouseClicked(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-ban-32.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(front, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(front)
                    .addComponent(cancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ReturnSaleBody.setLayout(new java.awt.CardLayout());

        by_order3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        by_order3.setText("By customer");
        by_order3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        by_order2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        by_order2.setText("By Date");
        by_order2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        by_order1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        by_order1.setText("By Product Name");
        by_order1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        by_order.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        by_order.setText("By Order Number");
        by_order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SelectionMeansLayout = new javax.swing.GroupLayout(SelectionMeans);
        SelectionMeans.setLayout(SelectionMeansLayout);
        SelectionMeansLayout.setHorizontalGroup(
            SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionMeansLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(by_order)
                    .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(by_order2)
                        .addComponent(by_order1)
                        .addComponent(by_order3)))
                .addContainerGap(676, Short.MAX_VALUE))
        );
        SelectionMeansLayout.setVerticalGroup(
            SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionMeansLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(by_order)
                .addGap(18, 18, 18)
                .addComponent(by_order1)
                .addGap(12, 12, 12)
                .addComponent(by_order2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(by_order3)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectionMeans, "card2");

        OrdersTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        OrdersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrdersTable);

        javax.swing.GroupLayout SelectRowLayout = new javax.swing.GroupLayout(SelectRow);
        SelectRow.setLayout(SelectRowLayout);
        SelectRowLayout.setHorizontalGroup(
            SelectRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        SelectRowLayout.setVerticalGroup(
            SelectRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectRow, "card3");

        SelectionArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        qtyamounttobereturned.setText("Quantity to be returned");

        savebutton.setText("Save");

        prdnametobereturned.setText("Product name to be returned");

        javax.swing.GroupLayout SelectionAreaLayout = new javax.swing.GroupLayout(SelectionArea);
        SelectionArea.setLayout(SelectionAreaLayout);
        SelectionAreaLayout.setHorizontalGroup(
            SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionAreaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prdnametobereturned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SelectionAreaLayout.createSequentialGroup()
                        .addComponent(qtyamounttobereturned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savebutton)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        SelectionAreaLayout.setVerticalGroup(
            SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionAreaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(prdnametobereturned)
                .addGap(18, 18, 18)
                .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyamounttobereturned)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(savebutton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SelectAmountLayout = new javax.swing.GroupLayout(SelectAmount);
        SelectAmount.setLayout(SelectAmountLayout);
        SelectAmountLayout.setHorizontalGroup(
            SelectAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectAmountLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(SelectionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        SelectAmountLayout.setVerticalGroup(
            SelectAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectAmountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(SelectionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectAmount, "card4");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Return Method"));

        jRadioButton1.setText("Credit");

        jRadioButton2.setText("Cash");

        jRadioButton3.setText("Check");

        jRadioButton4.setText("Credit");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("comments");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReturnMethodLayout = new javax.swing.GroupLayout(ReturnMethod);
        ReturnMethod.setLayout(ReturnMethodLayout);
        ReturnMethodLayout.setHorizontalGroup(
            ReturnMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnMethodLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );
        ReturnMethodLayout.setVerticalGroup(
            ReturnMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnMethodLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(ReturnMethod, "card5");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-document-delivery-16.png"))); // NOI18N
        jLabel2.setText("Select Delivery Company");

        jLabel3.setText("Cost");

        jRadioButton5.setText("Free - (No cost)");

        javax.swing.GroupLayout SelectShippingLayout = new javax.swing.GroupLayout(SelectShipping);
        SelectShipping.setLayout(SelectShippingLayout);
        SelectShippingLayout.setHorizontalGroup(
            SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectShippingLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 827, Short.MAX_VALUE)
                .addGroup(SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        SelectShippingLayout.setVerticalGroup(
            SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectShippingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectShipping, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReturnSaleBody, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnSaleBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersTableMouseClicked
        // Get present row when clicked
        row = OrdersTable.getSelectedRow();
        column = OrdersTable.getColumnCount();
        String prd_name = ReturnModel.getValueAt(row, 2).toString();
        String id = ReturnModel.getValueAt(row, 1).toString();
        String sellingquantity = ReturnModel.getValueAt(row, 3).toString();
        String price = ReturnModel.getValueAt(row, 4).toString();
        String discount = ReturnModel.getValueAt(row, 5).toString();
        this.prd_details.add(id);
        this.prd_details.add(prd_name);
        this.prd_details.add(price);
        this.prd_details.add(sellingquantity);
        this.prd_details.add(discount);
    }//GEN-LAST:event_OrdersTableMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // Closing
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void frontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frontMouseClicked
        // TODO add your handling code here:
        switch (clickcount) {
            case 0:
                SelectionMeans.setVisible(false);
                SelectRow.setVisible(true);
                front.setText("Next");
                back.setEnabled(false);
                break;
            case 1:
                SelectRow.setVisible(false);
                SelectAmount.setVisible(true);
                break;
            case 2:
                SelectAmount.setVisible(false);
                ReturnMethod.setVisible(true);
                break;
            case 3:
                ReturnMethod.setVisible(false);
                SelectShipping.setVisible(true);
                front.setText("Finish");
                break;
                
            default:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                SelectAmount.setVisible(false);
                this.clickcount = 0;
                front.setText("Next");
                break;
        }
        
        
        if (this.clickcount < 4) {
            if (this.clickcount >= 0) {
                this.clickcount += 1;
            }
        }
        System.out.println(clickcount);
    }//GEN-LAST:event_frontMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        switch (clickcount) {
            case 1:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                break;
            case 2:
                SelectRow.setVisible(true);
                SelectAmount.setVisible(false);
                break;
            default:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                SelectAmount.setVisible(false);
                this.clickcount = 0;
        }
        if (this.clickcount < 3) {
            if (this.clickcount > 0) {
                this.clickcount -= 1;
            }
        }
         System.out.println(clickcount);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    /**
     * Function to all the sales status
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     * @throws java.text.ParseException
     */
    public final void loadJtableValues() throws SQLException,
            ClassNotFoundException, ParseException {
        if (ReturnModel != null) {
            ReturnModel.setRowCount(0);
        }
        ReturnList = listOrders();
        for (int i = 0; i < ReturnList.size(); i++) {
            System.out.println("Present sale" + ReturnList.get(i).product);
            Object[] obj = {
                ReturnList.get(i).selected,
                (ReturnList.get(i).orderid).toUpperCase(),
                (ReturnList.get(i).product).toUpperCase(),
                (ReturnList.get(i).quantity).toUpperCase(),
                (ReturnList.get(i).listprice),
                (ReturnList.get(i).discount)
            };
            ReturnModel.addRow(obj);
        }
        OrdersTable.repaint();
        OrdersTable.revalidate();
    }

    /*end of it*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ReturnProduct().setVisible(true);
            } catch (SQLException | ClassNotFoundException | ParseException ex) {
                Logger.getLogger(ReturnProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JTable OrdersTable;
    private javax.swing.JPanel ReturnMethod;
    private javax.swing.JPanel ReturnSaleBody;
    private javax.swing.JPanel SelectAmount;
    private javax.swing.JPanel SelectRow;
    private javax.swing.JPanel SelectShipping;
    private javax.swing.JPanel SelectionArea;
    private javax.swing.JPanel SelectionMeans;
    private javax.swing.JLabel back;
    private javax.swing.JRadioButton by_order;
    private javax.swing.JRadioButton by_order1;
    private javax.swing.JRadioButton by_order2;
    private javax.swing.JRadioButton by_order3;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel front;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel prdnametobereturned;
    private javax.swing.JLabel qtyamounttobereturned;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
}
