/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Products;

import Classes.AbstractClasses.Order;
import Classes.AbstractClasses.ProductDetails;
import static Classes.Functions.Crudes.addFromCSVFile;

import static Classes.Functions.Orders.listOrders;

import Classes.Functions.Products;
import static Classes.Functions.Products.checkCodeValidity;
import static Classes.Utilities.OS.path;
import static Classes.Utilities.OS.systempath;
import Classes.Utilities.RandomNumbers;
import static Classes.Utilities.RandomNumbers.generateNumber;
import Classes.Utilities.SearchEngine;
import Interface.Sale;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nkanabo
 */
public final class RegisterProduct extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    /*Sales variables declaration*/
    int row, column, clickcount;
    Object[] columnNames = {"Select", "Order Id", "Product",
        "Quantity", "List price", "Discount"
    };
    ArrayList<Order> ReturnList;

    DefaultTableModel ReturnModel = new DefaultTableModel(0, 0) {
        @Override
        public Class getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return Boolean.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;
                default:
                    return String.class;
            }
        }
    };
    int pos = 0;

    //Default list fot auto completion
    private final DefaultListModel brandsmodel;

    public ArrayList<String> prd_details = new ArrayList<>();
    JFileChooser browseFile = new JFileChooser();

    /*End of variables declaration*/
    /**
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     * @throws java.text.ParseException
     */
    public RegisterProduct() throws SQLException,
            ClassNotFoundException, ParseException {
        FlatGitHubIJTheme.setup();
        initComponents();
        CSV_Label.setToolTipText("Insert brands from "+systempath);
        showImage(pos);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        ReturnList = new ArrayList<>();
        // add header in table model     
        ReturnModel.setColumnIdentifiers(columnNames);
        OrdersTable.setModel(ReturnModel);
        loadJtableValues();

        //Initiating the variables
        
        jPopupMenu1.add(Autocomplete);
        brandsmodel = new DefaultListModel();
        autocompleteProducts.setModel(brandsmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Autocomplete = new javax.swing.JPanel();
        autocompleteProducts = new javax.swing.JList<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        BrandsPopMenu = new javax.swing.JPopupMenu();
        Header = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        Bundle = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        Supplies = new javax.swing.JLabel();
        Options = new javax.swing.JLabel();
        Expiration = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ReturnSaleBody = new javax.swing.JPanel();
        SelectionMeans = new javax.swing.JPanel();
        Code = new javax.swing.JLabel();
        GTIN = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cameraLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        costlabel = new javax.swing.JLabel();
        salepriceicon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        codeinput = new javax.swing.JTextField();
        barcodeinput = new javax.swing.JTextField();
        descriptioninput = new javax.swing.JTextField();
        brandname = new javax.swing.JTextField();
        categoryname = new javax.swing.JTextField();
        locationinput = new javax.swing.JTextField();
        costinput = new javax.swing.JTextField();
        salepriceinput = new javax.swing.JTextField();
        stocklevelinput = new javax.swing.JTextField();
        unitofmeasure = new javax.swing.JComboBox<>();
        minimumstocklevelinput = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentsinput = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        CSV_Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SelectRow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersTable = new javax.swing.JTable();
        SelectAmount = new javax.swing.JPanel();
        SelectionArea = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        qtyamounttobereturned = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        prdnametobereturned = new javax.swing.JLabel();
        ReturnMethod = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        SelectShipping = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();

        autocompleteProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        autocompleteProducts.setForeground(new java.awt.Color(0, 153, 255));
        autocompleteProducts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        autocompleteProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autocompleteProductsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AutocompleteLayout = new javax.swing.GroupLayout(Autocomplete);
        Autocomplete.setLayout(AutocompleteLayout);
        AutocompleteLayout.setHorizontalGroup(
            AutocompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutocompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autocompleteProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        AutocompleteLayout.setVerticalGroup(
            AutocompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutocompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autocompleteProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPopupMenu1.setFocusable(false);

        BrandsPopMenu.setBackground(new java.awt.Color(204, 204, 255));
        BrandsPopMenu.setForeground(new java.awt.Color(153, 153, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setBorder(new javax.swing.border.MatteBorder(null));

        Data.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Data.setText("Data");
        Data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMouseClicked(evt);
            }
        });

        Bundle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bundle.setText("Bundle");
        Bundle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bundle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BundleMouseClicked(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-ban-32.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        Tax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tax.setText("Tax");
        Tax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaxMouseClicked(evt);
            }
        });

        Supplies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Supplies.setText("Suppliers");
        Supplies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Supplies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuppliesMouseClicked(evt);
            }
        });

        Options.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Options.setText("Options");
        Options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionsMouseClicked(evt);
            }
        });

        Expiration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Expiration.setText("Expiration");
        Expiration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Expiration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpirationMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-checkmark-32.png"))); // NOI18N
        jLabel10.setText("Save");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel)
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bundle)
                .addGap(24, 24, 24)
                .addComponent(Tax)
                .addGap(24, 24, 24)
                .addComponent(Supplies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Options)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Expiration)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bundle)
                    .addComponent(cancel)
                    .addComponent(Tax)
                    .addComponent(Supplies)
                    .addComponent(Options)
                    .addComponent(Expiration)
                    .addComponent(jLabel10)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
        );

        ReturnSaleBody.setLayout(new java.awt.CardLayout());

        SelectionMeans.setForeground(new java.awt.Color(51, 153, 255));
        SelectionMeans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Code.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Code.setText("Code");

        GTIN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        GTIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-barcode-16.png"))); // NOI18N
        GTIN.setText("EAN/GTIN");

        category.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        category.setText("Category");

        brand.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        brand.setText("Brand");

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        DescriptionLabel.setText("Description");

        LocationLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LocationLabel.setText("Location");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Click here to select the image of this product");

        cameraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cameraLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-camera-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cameraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cameraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(174, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap()))
        );

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));

        costlabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        costlabel.setText("Cost");

        salepriceicon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        salepriceicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-cash-32.png"))); // NOI18N
        salepriceicon.setText("Sale Price");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Stock Level");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Unit of Measure");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Minimum stock Limit");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Comments");

        jSeparator2.setBackground(new java.awt.Color(51, 153, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));

        codeinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        barcodeinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        descriptioninput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        brandname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        brandname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandnameKeyReleased(evt);
            }
        });

        categoryname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        categoryname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                categorynameKeyReleased(evt);
            }
        });

        locationinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        costinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        salepriceinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        stocklevelinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        unitofmeasure.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        unitofmeasure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        minimumstocklevelinput.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        commentsinput.setColumns(20);
        commentsinput.setRows(5);
        jScrollPane3.setViewportView(commentsinput);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Automatic");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox2.setText("Do not Control stock");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox3.setText("Change price during sale");
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CSV_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-import-csv-16.png"))); // NOI18N
        CSV_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSV_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSV_LabelMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-tanzania-16.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SelectionMeansLayout = new javax.swing.GroupLayout(SelectionMeans);
        SelectionMeans.setLayout(SelectionMeansLayout);
        SelectionMeansLayout.setHorizontalGroup(
            SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionMeansLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectionMeansLayout.createSequentialGroup()
                                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Code, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GTIN)
                                            .addComponent(category)
                                            .addGroup(SelectionMeansLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DescriptionLabel)
                                                    .addComponent(brand)
                                                    .addComponent(LocationLabel)
                                                    .addComponent(costlabel)))))
                                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(salepriceicon)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionMeansLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectionMeansLayout.createSequentialGroup()
                                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(codeinput, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                            .addComponent(barcodeinput))
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(categoryname, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                                        .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CSV_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descriptioninput, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationinput, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(SelectionMeansLayout.createSequentialGroup()
                                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(unitofmeasure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stocklevelinput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                        .addComponent(salepriceinput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(costinput, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(minimumstocklevelinput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SelectionMeansLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(72, 72, 72)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 167, Short.MAX_VALUE))))
        );
        SelectionMeansLayout.setVerticalGroup(
            SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionMeansLayout.createSequentialGroup()
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Code)
                            .addComponent(codeinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GTIN)
                            .addComponent(barcodeinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category)
                            .addComponent(categoryname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brand))
                            .addComponent(CSV_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptioninput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationLabel)))
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costlabel))
                .addGap(18, 18, 18)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salepriceinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salepriceicon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(stocklevelinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitofmeasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumstocklevelinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SelectionMeansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(SelectionMeansLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );

        ReturnSaleBody.add(SelectionMeans, "card2");

        OrdersTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        OrdersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrdersTable);

        javax.swing.GroupLayout SelectRowLayout = new javax.swing.GroupLayout(SelectRow);
        SelectRow.setLayout(SelectRowLayout);
        SelectRowLayout.setHorizontalGroup(
            SelectRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE)
        );
        SelectRowLayout.setVerticalGroup(
            SelectRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectRowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectRow, "card3");

        SelectionArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        qtyamounttobereturned.setText("Quantity to be returned");

        savebutton.setText("Save");

        prdnametobereturned.setText("Product name to be returned");

        javax.swing.GroupLayout SelectionAreaLayout = new javax.swing.GroupLayout(SelectionArea);
        SelectionArea.setLayout(SelectionAreaLayout);
        SelectionAreaLayout.setHorizontalGroup(
            SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionAreaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prdnametobereturned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SelectionAreaLayout.createSequentialGroup()
                        .addComponent(qtyamounttobereturned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savebutton)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        SelectionAreaLayout.setVerticalGroup(
            SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionAreaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(prdnametobereturned)
                .addGap(18, 18, 18)
                .addGroup(SelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyamounttobereturned)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(savebutton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SelectAmountLayout = new javax.swing.GroupLayout(SelectAmount);
        SelectAmount.setLayout(SelectAmountLayout);
        SelectAmountLayout.setHorizontalGroup(
            SelectAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectAmountLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(SelectionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        SelectAmountLayout.setVerticalGroup(
            SelectAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectAmountLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(SelectionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectAmount, "card4");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Return Method"));

        jRadioButton1.setText("Credit");

        jRadioButton2.setText("Cash");

        jRadioButton3.setText("Check");

        jRadioButton4.setText("Credit");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("comments");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReturnMethodLayout = new javax.swing.GroupLayout(ReturnMethod);
        ReturnMethod.setLayout(ReturnMethodLayout);
        ReturnMethodLayout.setHorizontalGroup(
            ReturnMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnMethodLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        ReturnMethodLayout.setVerticalGroup(
            ReturnMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnMethodLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(ReturnMethod, "card5");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-document-delivery-16.png"))); // NOI18N
        jLabel2.setText("Select Delivery Company");

        jLabel3.setText("Cost");

        jRadioButton5.setText("Free - (No cost)");

        javax.swing.GroupLayout SelectShippingLayout = new javax.swing.GroupLayout(SelectShipping);
        SelectShipping.setLayout(SelectShippingLayout);
        SelectShippingLayout.setHorizontalGroup(
            SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectShippingLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 914, Short.MAX_VALUE)
                .addGroup(SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        SelectShippingLayout.setVerticalGroup(
            SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectShippingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SelectShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addContainerGap(727, Short.MAX_VALUE))
        );

        ReturnSaleBody.add(SelectShipping, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReturnSaleBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ReturnSaleBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersTableMouseClicked
        // Get present row when clicked
        row = OrdersTable.getSelectedRow();
        column = OrdersTable.getColumnCount();
        String prd_name = ReturnModel.getValueAt(row, 2).toString();
        String id = ReturnModel.getValueAt(row, 1).toString();
        String sellingquantity = ReturnModel.getValueAt(row, 3).toString();
        String price = ReturnModel.getValueAt(row, 4).toString();
        String discount = ReturnModel.getValueAt(row, 5).toString();
        this.prd_details.add(id);
        this.prd_details.add(prd_name);
        this.prd_details.add(price);
        this.prd_details.add(sellingquantity);
        this.prd_details.add(discount);
    }//GEN-LAST:event_OrdersTableMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // Closing
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void BundleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BundleMouseClicked
        // TODO add your handling code here:
        switch (clickcount) {
            case 0:
                SelectionMeans.setVisible(false);
                SelectRow.setVisible(true);
                Bundle.setText("Next");
                Data.setEnabled(false);
                break;
            case 1:
                SelectRow.setVisible(false);
                SelectAmount.setVisible(true);
                break;
            case 2:
                SelectAmount.setVisible(false);
                ReturnMethod.setVisible(true);
                break;
            case 3:
                ReturnMethod.setVisible(false);
                SelectShipping.setVisible(true);
                Bundle.setText("Finish");
                break;

            default:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                SelectAmount.setVisible(false);
                this.clickcount = 0;
                Bundle.setText("Next");
                break;
        }

        if (this.clickcount < 4) {
            if (this.clickcount >= 0) {
                this.clickcount += 1;
            }
        }
    }//GEN-LAST:event_BundleMouseClicked

    private void DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMouseClicked
        switch (clickcount) {
            case 1:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                break;
            case 2:
                SelectRow.setVisible(true);
                SelectAmount.setVisible(false);
                break;
            default:
                SelectionMeans.setVisible(true);
                SelectRow.setVisible(false);
                SelectAmount.setVisible(false);
                this.clickcount = 0;
        }
        if (this.clickcount < 3) {
            if (this.clickcount > 0) {
                this.clickcount -= 1;
            }
        }
    }//GEN-LAST:event_DataMouseClicked

    private void TaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxMouseClicked

    private void SuppliesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuppliesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SuppliesMouseClicked

    private void OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionsMouseClicked

    private void ExpirationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpirationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpirationMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //Arraylist for storing products
        ArrayList<ProductDetails> product = new ArrayList<>();
        Object[] obj = {
            codeinput.getText(),
            barcodeinput.getText(),
            categoryname.getText(),
            brandname.getText(),
            descriptioninput.getText(),
            locationinput.getText(),
            costinput.getText(),
            salepriceinput.getText(),
            stocklevelinput.getText(),
            unitofmeasure.getSelectedItem(),
            minimumstocklevelinput.getText(),
            commentsinput.getText()
        };
        File selectedFile = browseFile.getSelectedFile();
        String filename = browseFile.getSelectedFile().getName();
        try {
            Products.RegisterProduct(obj);
            saveImage(selectedFile, filename);
        } catch (URISyntaxException | ClassNotFoundException
                | ParseException | IOException ex) {
            Logger.getLogger(RegisterProduct.class.getName())
                    .log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel10MouseClicked

    private void autocompleteProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autocompleteProductsMouseClicked
        //if the products drop down list is created.
        int index = autocompleteProducts.getSelectedIndex();
        String s = (String) autocompleteProducts.getSelectedValue();
        brandname.setText(s);
    }//GEN-LAST:event_autocompleteProductsMouseClicked

    private void CSV_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSV_LabelMouseClicked
        // Upload excell mouse button clicked:
        FileNameExtensionFilter fnef;
        fnef = new FileNameExtensionFilter("IMAGES",
                "png", "jpg", "jpeg");
        JFileChooser csvFileChooser = new JFileChooser();
        csvFileChooser.addChoosableFileFilter(fnef);
        int showOpenDialog = csvFileChooser.showOpenDialog(null);
        if (showOpenDialog == APPROVE_OPTION) {
            notificationLabel("wait");
            File selectedFile = csvFileChooser.getSelectedFile();
            String filename = csvFileChooser.getSelectedFile().getName();
            String SelectedFile = selectedFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, SelectedFile);
            try {
                addFromCSVFile();
            } catch (SQLException | ClassNotFoundException | IOException ex) {
                Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CSV_LabelMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            int randomNumber = generateNumber();
            try {
                // Here i am setting text of the code to something random:
                if (!checkCodeValidity(
                        String.valueOf(randomNumber)
                )) {
                    codeinput.setText("" + randomNumber);
                    codeinput.setEditable(false);
                } else {
                }

            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            codeinput.setText("");
            codeinput.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void categorynameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categorynameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_categorynameKeyReleased

    private void brandnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandnameKeyReleased
        // Searching begins
        String Search = brandname.getText().trim();
        if (Search.equals("")) {
            /* this means there is nothing provided from users end point
            so as to provide the auto complete queries. */
        } else {
            brandsmodel.removeAllElements();
            SearchEngine searchEngine = new SearchEngine();
            try {
                //for(String item:searchEngine.ProductsearchSuggestions(Search)){
                for (String item : searchEngine.brandSearch(Search)) {
                    brandsmodel.addElement(item);
                }
            } catch (ClassNotFoundException | ParseException | SQLException ex) {
                Logger.getLogger(RegisterProduct.class.getName())
                        .log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
            jPopupMenu1.show(brandname, 0, brandname.getHeight());
        }
    }//GEN-LAST:event_brandnameKeyReleased

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // Uploading the button into the resources folder
        FileNameExtensionFilter fnef
                = new FileNameExtensionFilter("IMAGES",
                        "png", "jpg", "jpeg");
        browseFile.addChoosableFileFilter(fnef);
        int showOpenDialog = browseFile.showOpenDialog(null);
        if (showOpenDialog == APPROVE_OPTION) {
            File selectedFile = browseFile.getSelectedFile();
            String filename = browseFile.getSelectedFile().getName();
            String SelectedImage = selectedFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, SelectedImage);
            ImageIcon ii = new ImageIcon(SelectedImage);
            //Resizing unage to fit the JLabel
            Image image;
            image = ii.getImage()
                    .getScaledInstance(cameraLabel.getWidth(),
                            cameraLabel.getHeight(),
                            Image.SCALE_SMOOTH);
            cameraLabel.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            // When the user requests for Tienda pre defined world brands
            addFromCSVFile();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    public String[] getImages() {
        String imageUrl = systempath;
        File file = new File(systempath);
        String[] imagesList = file.list();
        return imagesList;
    }

    public void showImage(int index) {
        String[] imagesList = getImages();
        String imageName = imagesList[index];
        ImageIcon icon = new ImageIcon(systempath + imageName);
        Image image;
        image = icon.getImage()
                .getScaledInstance(cameraLabel.getWidth(),
                        cameraLabel.getHeight(),
                        Image.SCALE_SMOOTH);
        cameraLabel.setIcon(new ImageIcon(image));
    }

    public void saveImage(File fname, String Selectedfilename) throws IOException {
        File destinationFile = new File(systempath + Selectedfilename);
        try {
            Files.move(fname.toPath(), destinationFile.toPath(),
                    StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {

            /*
        JOptionPane.showMessageDialog(null,
        "Failed to save Image" + e);
             */
            e.printStackTrace();

        }
        /*
        JOptionPane.showMessageDialog(null,
        "Successfully saved item");
         */
    }

    /**
     * @param args the command line arguments
     */
    /**
     * Function to all the sales status
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     * @throws java.text.ParseException
     */
    public final void loadJtableValues() throws SQLException,
            ClassNotFoundException, ParseException {
        if (ReturnModel != null) {
            ReturnModel.setRowCount(0);
        }
        ReturnList = listOrders();
        for (int i = 0; i < ReturnList.size(); i++) {
            Object[] obj = {
                ReturnList.get(i).selected,
                (ReturnList.get(i).orderid).toUpperCase(),
                (ReturnList.get(i).product).toUpperCase(),
                (ReturnList.get(i).quantity).toUpperCase(),
                (ReturnList.get(i).listprice),
                (ReturnList.get(i).discount)
            };
            ReturnModel.addRow(obj);
        }
        OrdersTable.repaint();
        OrdersTable.revalidate();
    }

    public void notificationLabel(String type) {
        switch (type) {
            case "wait":
                CSV_Label.setIcon(
                        new javax.swing.ImageIcon(getClass()
                                .getResource("/resources/images/Reload-0.6s-18px.gif")));
                break;

            case "complete":
                CSV_Label.setIcon(
                        new javax.swing.ImageIcon(getClass()
                                .getResource("/resources/images/Reload-0.6s-18px.gif")));
                try {
                    int secondsToSleep = 2;
                    Thread.sleep(secondsToSleep * 1000);
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
                CSV_Label.setIcon(
                        new javax.swing.ImageIcon(getClass()
                                .getResource("/resources/images/icons8-checkmark-32.png")));
                break;
        }
    }

    /*end of it*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new RegisterProduct().setVisible(true);
            } catch (SQLException | ClassNotFoundException | ParseException ex) {
                Logger.getLogger(RegisterProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Autocomplete;
    private javax.swing.JPopupMenu BrandsPopMenu;
    private javax.swing.JLabel Bundle;
    private javax.swing.JLabel CSV_Label;
    private javax.swing.JLabel Code;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel Expiration;
    private javax.swing.JLabel GTIN;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JLabel Options;
    private javax.swing.JTable OrdersTable;
    private javax.swing.JPanel ReturnMethod;
    private javax.swing.JPanel ReturnSaleBody;
    private javax.swing.JPanel SelectAmount;
    private javax.swing.JPanel SelectRow;
    private javax.swing.JPanel SelectShipping;
    private javax.swing.JPanel SelectionArea;
    private javax.swing.JPanel SelectionMeans;
    private javax.swing.JLabel Supplies;
    private javax.swing.JLabel Tax;
    private javax.swing.JList<String> autocompleteProducts;
    private javax.swing.JTextField barcodeinput;
    private javax.swing.JLabel brand;
    private javax.swing.JTextField brandname;
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel category;
    private javax.swing.JTextField categoryname;
    private javax.swing.JTextField codeinput;
    private javax.swing.JTextArea commentsinput;
    private javax.swing.JTextField costinput;
    private javax.swing.JLabel costlabel;
    private javax.swing.JTextField descriptioninput;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField locationinput;
    private javax.swing.JTextField minimumstocklevelinput;
    private javax.swing.JLabel prdnametobereturned;
    private javax.swing.JLabel qtyamounttobereturned;
    private javax.swing.JLabel salepriceicon;
    private javax.swing.JTextField salepriceinput;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField stocklevelinput;
    private javax.swing.JComboBox<String> unitofmeasure;
    // End of variables declaration//GEN-END:variables
}
